apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: nginx
          image: gihyodocker/nginx-proxy:latest
          env:
            - name: BACKEND_HOST
              value: "8080"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "10Mi"
              cpu: "25m"
        - name: echo
          image: gihyodocker/echo:latest
          ports:
            - containerPort: 8080
