apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-spring
  labels:
    app: echo
    release: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
      release: spring
  template:
    metadata:
      labels:
        app: echo
        release: spring
    spec:
      containers:
        - name: nginx
          image: gihyodocker/nginx-proxy:latest
          env:
            - name: BACKEND_HOST
              value: "8080"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "10Mi"
              cpu: "25m"
        - name: echo
          image: gihyodocker/echo:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "10Mi"
              cpu: "25m"
      restartPolicy: Always # If container continues crash, Pod status will be CrashLoopBackOff.
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-summer
  labels:
    app: echo
    release: summer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
      release: summer
  template:
    metadata:
      labels:
        app: echo
        release: summer
    spec:
      containers:
        - name: nginx
          image: gihyodocker/nginx-proxy:latest
          env:
            - name: BACKEND_HOST
              value: "8080"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "10Mi"
              cpu: "25m"
        - name: echo
          image: gihyodocker/echo:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "10Mi"
              cpu: "25m"
